CREATE DATABASE IF NOT EXISTS multapps_dev;
USE multapps_dev;

CREATE TABLE IF NOT EXISTS categoria (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	data_alteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	status ENUM ('intivo','ativo','excluido') NOT NULL
);

CREATE TABLE IF NOT EXISTS Produtos (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	categoria_id INT NOT NULL,
	nome VARCHAR(100) NOT NULL,
	quantidade_estoque INT NOT NULL,
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	data_alteracao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	status ENUM ('intivo','ativo','excluido') NOT NULL,
	FOREIGN KEY (categoria_id) REFERENCES categoria(id)
)
